### PR TITLE
Centered cards and made them mobile-responsive.

### LINKED ISSUE #21: Center the div element for each event
each event card is a div spanning the entire width of the page. 

**Center the div element.** The associated css is /assets/css/mainpage.css

Screen Shot 2019-10-19 at 6 36 35 PM

**Make sure it scales in mobile too**

Screen Shot 2019-10-19 at 6 35 24 PM

### PR DESCRIPTION
**Pull request by justinlyan**
Fixes https://github.com/sfusurge/sfusurge.github.io/issues/21

Mobile:

Web:
Screen Shot 2019-10-19 at 10 25 34 PM

### CODE REVIEW

**Comment by AmirNaghibi** [comment]
This is a fantastic @justinlyan!! I really appreciate your help! 
would it be possible to have two cards in a row for the desktop version? and make the cards a bit smaller? This would help us a lot😄

If that's gonna take too much of your time, don't worry about it :) I will merge the PR and figure something out later

**Comment by justinlyan** [comment]
> This is a fantastic @justinlyan!! I really appreciate your help!
> would it be possible to have two cards in a row for the desktop version? and make the cards a bit smaller? This would help us a lot😄
> 
> If that's gonna take too much of your time, don't worry about it :) I will merge the PR and figure something out later

Sure I can work on it! Did you still want the text-shadow on the cards? I think if we put the cards in a row it might look better without the shadow. Your thoughts?

**Comment by AmirNaghibi** [comment]
yeah I agree. we don't need the shadows.
Also, could you modify the files outside of the _site directory instead? 

you can modify files in the **_pages** directory or the **index.html** in the project root directory.

because all the files inside the _site directory will be regenerated after running **bundle exec jekyll serve** and modifying files in _sites won't work

**Comment by justinlyan** [comment]
The cards are now on the same row. I also made the cards smaller from 40% to 30%. Let me know what you think and if there are any other changes you'd like me to make! 
Screen Shot 2019-10-20 at 4 16 05 PM

**Comment by AmirNaghibi** [comment]
I have merged the PR! Thanks @justinlyan

**Pull request merged**
